services:
  php:
    build:
      context: .
      target: php_dev
    container_name: adventofcode-php
    volumes:
      - .:/app:cached
    environment:
      APP_ENV: dev
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: php -S 0.0.0.0:8000 -t public
